using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;

namespace EmpiresInSpace
{
    public partial class login : System.Web.UI.Page
    {


        private bool LoginDemoUser(int demoUserId)
        {
            this.SetSession(demoUserId);
            

            if (Response.IsClientConnected) //example from msdn
            {
                // If still connected, redirect
                // to another page. 
                string newUrl = ResolveUrl("Galaxy.aspx");
                Response.Redirect(newUrl, false);
                Context.ApplicationInstance.CompleteRequest();
                return true;
            }
            else
            {
                // If the browser is not connected
                // stop all response processing.
                Response.End();
                return false;
            }
        }

        private bool RegisterUser(int demoUserId, string startingRegion = null)
        {
            SpacegameServer.BC.BusinessConnector bc = (SpacegameServer.BC.BusinessConnector)Application["bs"];
            if (bc.userRegisterUser(demoUserId, startingRegion, true ))
            {
                this.SetSession(demoUserId);
                Response.Redirect("Galaxy.aspx");
                return true;
            }
            return false;
        }

        private bool DemoLoginCreate(int demoUserId)
        {
            SpacegameServer.BC.BusinessConnector bc = (SpacegameServer.BC.BusinessConnector)Application["bs"];
            //check if demoUser is really part of the game. If not, go to user creation routine                
            if (bc.UserExists(demoUserId))
            {
                return LoginDemoUser(demoUserId);
            }
            else
            {
                var StartingRegion = Application["StartingRegion"];
                return RegisterUser(demoUserId, StartingRegion != null ? StartingRegion.ToString() : null);
            }
        }

        private void SetSession(int userid)
        {
            SpacegameServer.Core.Core.Instance.writeToLog("Page_Load() 10 Set Session " + userid.ToString());
            Session["user"] = new Users(userid);
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            //There are three sources which userId to take:
            //1) userId provided manually in a demo environment in the settings panel
            //2) Demo userId from thw Web.config file
            //3) userId generated by using the logincode from the index page (standard login)

            // check if session variable exists
            // check if user is logged in
            // check if catchedid exists
            // 

            //in Demo games, a new user may be saved in the DemoId field. If yes, delete the previous session
            if (!LoginCheckCache()) return;

            //check if session variable already exists. If yes, user is already correctly logged in and may go to the game
            if (!LoginCheckSession()) return;

            //read demouser to force login to a specific user (for debugging)
            if (!LoginCheckDemoUser()) return;

            string loginCode = "";

            // at least one of them is broken
            if (!LoginCheckIndex(loginCode)) return;
            if (!LoginCheckIp(loginCode)) return;

            string redirectPath = System.Web.Configuration.WebConfigurationManager.AppSettings["index"].ToString();
            if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("Page_Load() 60 redirectPath " + redirectPath); }
            Response.Redirect(redirectPath);
        }

        private bool LoginCheckDemoUser()
        {
            string demoUser = System.Web.Configuration.WebConfigurationManager.AppSettings["demoUser"].ToString();
            if (!Int32.TryParse(demoUser, out int demoUserId)) demoUserId = 0;

            if (demoUserId > 0)
            {
                if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("Page_Load() 20 demoUserId " + demoUser); }
                DemoLoginCreate(demoUserId);
                return false;
            }

            return true;
        }

        private bool LoginCheckSession()
        {
            if (Session["user"] != null)
            {
                if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("Page_Load() 10 Response.Redirect(Galaxy.aspx); "); }
                Response.Redirect("Galaxy.aspx");
                return false;
            }
            return true;
        }

        private bool LoginCheckCache ()
        {
            var CachedIdObj = Application["DemoId"];
            if (CachedIdObj != null)
            {
                Session["user"] = null;
                int CachedId = (int)CachedIdObj;
                return !DemoLoginCreate(CachedId);
            }
            return true;
        }

        // TODO: fix
        private bool LoginCheckIndex (string loginCode)
        {
            //check if user is already logged in (via index page - comparison of loginCode and last hour)
            //checks game db
            if (Request.Params["login"] != null)
                loginCode = Request.Params["login"];

            if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("Page_Load() 30 checkLogin " + loginCode); }
            checkLogin(loginCode);
            if (Session["user"] != null)
            {
                if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("Page_Load() 40 Redirect "); }
                Response.Redirect("Galaxy.aspx");
                return false;
            }
            return true;
        }

        // TODO: fix
        private bool LoginCheckIp (string loginCode)
        { 
            //check if ip is part of index, and if registration can take place
            //also just logs in if player is already registered
            SpacegameServer.BC.BusinessConnector bc = (SpacegameServer.BC.BusinessConnector)Application["bs"];

            int userId = 0;
            if (checkIndexLogin(ref userId, loginCode))
            {
                if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("Page_Load() 50 userRegisterUser " + userId.ToString() + " |  " + loginCode); }
                if (bc.userRegisterUser(userId))
                {
                    this.SetSession(userId);
                    Response.Redirect("Galaxy.aspx");
                    return false;
                }
            }

            return true;
        }

        private bool checkIndexLogin(ref int userid, string loginCode)
        {
            bool ret = false;
            string ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["onlineInSpaceIndexConnectionString"].ToString();
            SqlConnection conn = new SqlConnection(ConnectionString);

            try
            {
                // 2. Open the connection
                conn.Open();

                //gets the userid for the ip-address. the ip-address has to have a logged-in date not smaller than an hour ago...
                string query = "[dbo].[UserCheckLoggedIn]";
                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter param2 = new SqlParameter();
                param2.ParameterName = "@UserHostAddress";
                param2.Value = Request.UserHostAddress;
                cmd.Parameters.Add(param2);

                SqlParameter code = new SqlParameter("@code", SqlDbType.Int);
                code.Value = loginCode;
                cmd.Parameters.Add(code);

                SqlParameter param4 = new SqlParameter("@userId", SqlDbType.Int);
                param4.Direction = ParameterDirection.Output;
                param4.Value = 0;
                cmd.Parameters.Add(param4);




                cmd.ExecuteNonQuery();

                if (Int32.TryParse(param4.Value.ToString(), out userid) && userid != 0)
                {
                    ret = true;
                }
                /*
                int id;
                if (Int32.TryParse(param4.Value.ToString(), out id) && id != 0)
                {
                    this.SetSession(id); 
                }*/

                conn.Close();
            }
            finally
            {
                // Close the connection
                if (conn != null)
                {
                    conn.Close();
                }
            }

            return ret;
        }

        public string getIp()
        {
            string clientIP;
            string ip = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
            if (!string.IsNullOrEmpty(ip))
            {
                string[] ipRange = ip.Trim().Split(',');
                clientIP = ipRange[0];
                //string[] ipRange2 = clientIP.Split(':');
                //clientIP = ipRange2[0];
            }
            else
                clientIP = Request.ServerVariables["REMOTE_ADDR"];


            return clientIP;
        }

        private void checkLogin(string loginCode)
        {
            SqlConnection conn;
            string activeConnection = System.Web.Configuration.WebConfigurationManager.AppSettings["activeConnection"].ToString();
            string ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings[activeConnection].ConnectionString;
            conn = new SqlConnection(ConnectionString);

            try
            {
                // 2. Open the connection
                conn.Open();

                if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("checkLogin() 10 loginCode " + loginCode); }
                if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("checkLogin() 20 Request.UserHostAddress " + Request.UserHostAddress); }
                if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("checkLogin() 21 HttpContext.Current.Request.UserHostAddress " + HttpContext.Current.Request.UserHostAddress); }
                // if (SpacegameServer.Core.Config.Instance.DebugLogin) { SpacegameServer.Core.Core.Instance.writeToLog("checkLogin() 22 ip " + ip); }


                //gets the userid for the ip-address. the ip-address has to have a logged-in date not smaller than an hour ago...
                string query = "[dbo].[UserCheckLoggedIn]";
                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter param2 = new SqlParameter();
                param2.ParameterName = "@UserHostAddress";
                if (String.IsNullOrEmpty(loginCode))
                {
                    param2.Value = Request.UserHostAddress;
                }
                else
                {
                    param2.Value = loginCode;
                }
                cmd.Parameters.Add(param2);

                SqlParameter param4 = new SqlParameter("@userId", SqlDbType.Int);
                param4.Direction = ParameterDirection.Output;
                param4.Value = 0;
                cmd.Parameters.Add(param4);

                cmd.ExecuteNonQuery();

                int userId;
                if (Int32.TryParse(param4.Value.ToString(), out userId) && userId != 0)
                {
                    this.SetSession(userId);
                }

                conn.Close();
            }
            finally
            {
                // Close the connection
                if (conn != null)
                {
                    conn.Close();
                }
            }
        }

        public string userLanguage()
        {
            return Request.UserLanguages[0].Substring(0, 2);

        }
        protected void loginTest()
        {
            string demoUser = System.Web.Configuration.WebConfigurationManager.AppSettings["demoUser"].ToString();
            this.SetSession(Int16.Parse(demoUser));

            return;
        }


    }

    class Users
    {
        public int id;

        public Users(int _id)
        {
            id = _id;
        }
    }
}